### ISSUE TITLE
Prod branch has been directly modified

### ISSUE THREAD

**Issue by IHS-Gdansk** [IHS-Gdansk/website#47]
Prod branch is meant for..well PROD. Master branch is also not something to be modified lightly, preferably through pull-requests. Direct Prod modification created merge conflicts between Prod and master that have to be merged manually. @KrzysiekES - would it be possible for you to clean up the conflicts?

**Comment by KrzysiekES** [comment]
I can resolve conflict between Prod and master, but you have to add me to contributors in this project because i dont have access to pushing commits, or if you dont want to let me do pushing, then you should do cherry-picking this two commits to master to resolve this conflict :

1.new text about IHS Markit, bigger logo on desktop
git cherry-pick 8941045
2.ihs color changes
git cherry-pick 711d377

I apologize for your trouble

**Comment by IHS-Gdansk** [comment]
I'm confused ;-)
You are on the collaborators' list already and I though you'd just used push rights to push to Prod directly ;-)
You're saying that those commits above were fast forwarded by someone else?

**Comment by KrzysiekES** [comment]
![image](https://cloud.githubusercontent.com/assets/5969362/19129544/f999b0b0-8b47-11e6-97b6-36f299fc5505.png)

i can resolve this conflict but i dont know why i cant push to the master.

**Comment by IHS-Gdansk** [comment]
Everything is clear - In a "self-defense" reaction I've made Prod and master branch protected so that only reviewed pull request are accepted - that's why now you see what you see ;-)
I can lift off the protection for you to fix things or you can apply the fixes in new pull request I would then merge.

**Comment by KrzysiekES** [comment]
Please lift off the protection, and i will fix this conflict.

**Comment by IHS-Gdansk** [comment]
Done

**Comment by KrzysiekES** [comment]
Thx, merge conflicts between Prod and master are resolved.
